"""add posttype and comment table

Revision ID: 1f6056736ae5
Revises: 0c58a720bc66
Create Date: 2020-05-23 06:29:54.837734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6056736ae5'
down_revision = '0c58a720bc66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posttype',
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('reply_id', sa.Integer(), nullable=True),
    sa.Column('up', sa.Integer(), nullable=True),
    sa.Column('down', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['reply_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('content', sa.String(length=500), nullable=True))
    op.add_column('posts', sa.Column('posttype_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('thumbnail_url', sa.String(length=300), nullable=True))
    op.add_column('posts', sa.Column('title', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'posts', 'posttype', ['posttype_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'thumbnail_url')
    op.drop_column('posts', 'posttype_id')
    op.drop_column('posts', 'content')
    op.drop_table('comment')
    op.drop_table('posttype')
    # ### end Alembic commands ###
